# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0906e87a3b692201ffefcb5e9b72bbad39dde09ca3f3b336f77906022e34be19f8e7b1802223f150446d9d3ccee526ccb2f3a1f76806a9c6450a18884579743a

test:
  secret_key_base: 2ed0474932144f9e09a3c33e5df41dda65d44f91d4d4f18896bd6d672440b6fc03a9e104531b71b329a1e6c411d5075c9d5bb5811c80f8350c6d34684ebe6222

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
